const name_list = [
  "Aing Maung",
  "Aung Aung",
  "Kaung Aung",
  "Maung Maung",
  "Kyaw Kyaw",
  "Asep Kulkas",
  "Beruang Sigma",
  "Nenek Mewing",
  "Kucing Buncit",
  "Gajah Melankolis",
  "Laba-laba Kawai",
  "Paus Lempeng",
  "Katak Sakti",
  "Kelinci Kacau",
  "Singa Kusut",
  "Tupai Terbang",
  "Beo Baper",
  "Cacing Gugup",
  "Ayam Gosip",
  "Buaya Berdasi",
  "Kura-kura Kepo",
  "Babi Belanja",
  "Kancil Kehabisan Nafas",
  "Domba Drama",
  "Tikus Teler",
  "Zebra Zaman Now",
  "Kadal Kepo",
  "Kupu-kupu Kreatif",
  "Ikan Sombong",
  "Kelelawar Kompleks",
  "Jerapah Jomblo",
  "Orangutan Onde-onde",
  "Belalang Belah Ketupat",
  "Cicak Cekikikan",
  "Lumba-lumba Lembek",
  "Burung Betah",
  "Anjing Anteng",
  "Kucing Kusam",
  "Gajah Gagal Move On",
  "Kucing Kepo",
  "Ayam Anomali",
  "Monyet Mager",
  "Kelinci Kuping Panjang",
  "Elang Edan",
  "Sapi Setia",
  "Kucing Kebelet Pipis",
  "Anjing Alay",
  "Babi Baper",
  "Kuda Kereta",
  "Capung Caper",
  "Ular Unggah-ungguh",
  "Harimau Hipster",
  "Singa Selow",
  "Kucing Kangkung",
  "Cicak Cinta",
  "Bebek Baper",
  "Kuda Karbit",
  "Kucing Keluyuran",
  "Landak Lengket",
  "Burung Bucu-bucu",
  "Kancil Ketakutan",
  "Bunglon Binal",
  "Katak Keren",
  "Sapi Sok Serius",
  "Musang Melow",
  "Hamster Hura-hura",
  "Kucing Kelaparan",
  "Kelelawar Kesurupan",
  "Ayam Artis",
  "Kucing Klepto",
  "Anjing Aneh",
  "Belalang Begadang",
  "Zebra Zonk",
  "Jerapah Janturan",
  "Kepiting Kesel",
  "Babi Betah",
  "Tupai Tertidur",
  "Cicak Cerewet",
  "Kuda Kusut",
  "Katak Ketiduran",
  "Belut Belok",
  "Gajah Genit",
  "Burung Betina",
  "Anjing Andalan",
  "Kucing Ketakutan",
  "Bunglon Bongkok",
  "Sapi Sengsara",
  "Kancil Kecil",
  "Harimau Hantu",
  "Kelinci Kencing",
  "Cicak Cinta-cintaan",
  "Monyet Muka Masam",
  "Ular Udik",
  "Beo Bening",
  "Kuda Kayu",
  "Singa Selancar",
  "Kucing Kepayang",
  "Ayam Aneh",
  "Burung Betrik",
  "Belalang Bimbang",
  "Tupai Tersesat",
  "Katak Ketemu Cinta",
  "Harimau Harap-harap Cemas",
  "Gajah Gembira",
  "Monyet Montok",
];

export { name_list };
